Feature/salesforce history mode
fivetran/dbt_salesforce_source pull request #14
Opened 2021-08-05 22:15 UTC by fivetran-joemarkiewicz

**Are you a current Fivetran customer?** 

Fivetran created PR

**What change(s) does this PR introduce?** 

This PR introduces the ability for a user to define variables if they have [history mode](https://fivetran.com/docs/getting-started/feature/history-mode) enabled on their Salesforce tables. This filter ensures only the active records are included.

Additionally, this PR introduces Postgres CircleCi testing to confirm Postrgres compatibility of the package.

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [X] No  (please provide explanation how the change is non breaking below.)

This PR only introduces a conditional that would not be a breaking change for existing users.

**Is this PR in response to a previously created Issue**

- [X] Yes, Issue #13 
- [ ] No 

**How did you test the PR changes?** 

 
- [ ] CircleCi  
- [ ] Other (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 
- [X] BigQuery
- [X] Redshift
- [X] Snowflake
- [X] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
⌛ 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2021-08-09 14:29 UTC, jcbmllgn commented
Thanks for working on this Joe!

2021-08-11 00:29 UTC, fivetran-jamie reviewed
looks great! couple of quick questions for you

2021-08-11 00:29 UTC, fivetran-jamie commented on .circleci/config.yml
> +            dbt run --vars '{salesforce__using_history_mode: true}' --target redshift
do we need to have `--full-refresh` in these first runs?

2021-08-11 00:29 UTC, fivetran-jamie commented on README.md
> +  using_user_history_mode: true         # false by default
wondering if `using_table_history_mode` is the best naming schema here, since what these variables actually do is filter out inactive records....are there folks who _are_ using history mode but don't want to filter in the package? this naming schema might be confusing for that case

2021-08-11 00:29 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__account_tmp.sql
> +where _fivetran_active
is a coalesce ever needed here?

2021-08-11 00:29 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__account_tmp.sql
> +where _fivetran_active
(same question for the other tmp tables)

2021-08-11 14:04 UTC, fivetran-joemarkiewicz commented on .circleci/config.yml
> +            dbt run --vars '{salesforce__using_history_mode: true}' --target redshift
Realistically this is not needed; however, with the update I made to the seed files the `--full-refresh` it was required to ensure the history model worked as intended.

2021-08-11 14:11 UTC, fivetran-joemarkiewicz commented on README.md
> +  using_user_history_mode: true         # false by default
The intention would be that customers with history mode enabled will want to filter out inactive records. If they want to keep the inactive records then they would keep this variable as false. I do understand how this naming convention could be confusions, but I am struggling to find the best name 🤔 

Let's chat more about this during standup.

2021-08-11 14:16 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_salesforce__account_tmp.sql
> +where _fivetran_active
I had this thought as well but decided not to include one as this is a Fivetran created field that should not be `null`. If it was `null` I was also struggling to determine what our stance would be if we want to filter this out or not.

Let's chat more about this one during standup too.

2021-08-11 16:52 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_salesforce__account_tmp.sql
> +where _fivetran_active
coalesce(_fivetran_active, false)

2021-08-11 17:01 UTC, fivetran-joemarkiewicz commented on README.md
> +  using_user_history_mode: true         # false by default
`using_history_mode_account_active_recrords` 🤷

2021-08-11 23:16 UTC, fivetran-joemarkiewicz commented on README.md
> +  using_user_history_mode: true         # false by default
final version is `using_account_history_mode_active_records`

2021-08-12 18:13 UTC, fivetran-jamie requested changes
mostly good! few comments that should be addressed before releasing

2021-08-12 18:13 UTC, fivetran-jamie commented on README.md
> +If you have Salesforce [History Mode](https://fivetran.com/docs/getting-started/feature/history-mode) enabled for your connector, the source tables will include all historical records. With history m
should we add an opinion here? like that the package is designed for dealing with non-historical data

2021-08-12 18:13 UTC, fivetran-jamie commented on dbt_project.yml
> +    using_user_history_mode: false
these should be `using_[table]_history_mode_active_records` right

2021-08-12 18:13 UTC, fivetran-jamie commented on integration_tests/ci/sample.profiles.yml
> +      schema: salesforce_source_integration_tests_2
why the `_2`?

2021-08-12 18:13 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__account_tmp.sql
> +where coalesce(_fivetran_active, false)
ah wait should we actually coalesce `_fivetran_active` to `true`, so that erring on the side of inclusion? similar to how we coalesce `_fivetran_deleted` to `false` in other packages?

2021-08-12 18:13 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__opportunity_tmp.sql
> +where coalesce(_fivetran_active, false)
same q as above

2021-08-12 18:13 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__user_role_tmp.sql
> +where coalesce(_fivetran_active, false)
same q as above

2021-08-12 18:13 UTC, fivetran-jamie commented on models/tmp/stg_salesforce__user_tmp.sql
> +where coalesce(_fivetran_active, false)
same q as above

2021-08-12 18:40 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_salesforce__account_tmp.sql
> +where coalesce(_fivetran_active, false)
Yeah we should stick to how we are doing this in other packages.

2021-08-12 18:40 UTC, fivetran-joemarkiewicz commented on dbt_project.yml
> +    using_user_history_mode: false
🤦 yup I missed that

2021-08-12 18:41 UTC, fivetran-joemarkiewicz commented on README.md
> +If you have Salesforce [History Mode](https://fivetran.com/docs/getting-started/feature/history-mode) enabled for your connector, the source tables will include all historical records. With history m
Good point. I will want to add that

2021-08-12 19:23 UTC, fivetran-jamie commented on integration_tests/ci/sample.profiles.yml
> +      schema: salesforce_source_integration_tests_2
peculiar ... perhaps we/circle ci's credentials lost drop schema privileges?

2021-08-12 19:25 UTC, fivetran-joemarkiewicz commented on integration_tests/ci/sample.profiles.yml
> +      schema: salesforce_source_integration_tests_2
I actually think it has something to do with my individual permissions. This has happened for circle runs where I run it locally and then it fails with the circle credentials. Kristin and I dug into this a while ago and found the drop schema priv worked fine when she had run locally first, but not with mine?

2021-08-12 19:26 UTC, fivetran-jamie approved these changes
lgtm!

2021-08-12 19:47 UTC, merged