updates to docs
fivetran/dbt_salesforce_source pull request #25
Opened 2022-04-28 19:35 UTC by fivetran-reneeli

Pull Request
**Are you a current Fivetran customer?** 

Internal
**What change(s) does this PR introduce?** 

as part of effort to standardize and update package docs
**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)
No, but a lot of facelift warrants a refresh
**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-04-28 19:37 UTC, fivetran-reneeli commented
I noticed since the package hasn't been updated recently, the `generate columns` [macro](https://github.com/fivetran/dbt_salesforce_source/tree/main/macros) is condensed into one file. Assuming we want to break this out too

2022-04-29 18:59 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for applying these updates! I have a few requests to change before approving that are both in the comment lines and listed out below. Let me know if you have any questions!

- [ ] I didn't mention this in the checklist (but am adding it now) that we want to be explicit with our jinja conditionals to make them easier to read. Would you mind updating the passthrough conditionals in the models to follow the format [here](https://github.com/fivetran/dbt_zendesk_source/blob/e41038ab6fc369aa9f9f01f802f981c9bb582abf/models/stg_zendesk__ticket.sql#L25-L30)
- [x] However, can you be sure to adjust the whitespace from the above changes as outlined [here](https://github.com/fivetran/dbt_style_guide/blob/updates/joe-additions/dbt_package_guidelines.md#jinja-formatting)
- [x] Add the `identifier` to each of the sources and include a variable for users to overwrite. See [here](https://github.com/fivetran/dbt_apple_store_source/blob/333d6fc5049f7579b04932993aa1effe8b4d323c/models/src_apple_store.yml#L10-L19) for an example.

2022-04-29 19:32 UTC, fivetran-reneeli commented on README v2.md
> +    salesforce_using_versions: false # Disable if you do not have the versions table, or if you do not want versions related metrics reported
My bad, didn't catch this, thank you!

2022-04-29 19:36 UTC, fivetran-reneeli commented on README v2.md
> +<p align="center">
Yes that's the plan, sorry if there was any confusion! Holding off so I can just move stuff over. I am going to replace the old README once we get this one finalized.

2022-05-03 14:35 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli I have a few change requests before this will be good to go! Let me know if you have any questions.

2022-05-03 14:35 UTC, fivetran-joemarkiewicz commented on models/stg_salesforce__opportunity.sql
> +    from fields
Can you adjust the formatting of the jinja conditional in this model

2022-05-03 14:35 UTC, fivetran-joemarkiewicz commented on models/stg_salesforce__user.sql
> +        --The below script allows for pass through columns.
Jinja conditional needs to be adjusted.

2022-05-03 14:35 UTC, fivetran-joemarkiewicz commented on README v2.md
> +    <default_source_table_name>_identifier: your_table_name
Can you adjust this to be `salesforce_<default_source_table_name>_identifier`

2022-05-05 20:42 UTC, fivetran-joemarkiewicz approved these changes
I have one question and a few requests to update the jinja formatting. Once you make those changes this will be good to merge to the release branch.

2022-05-05 20:42 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_salesforce__account_tmp.sql
> +{% if var('using_opportunity_history_mode_active_records', false) %}
Why was this changed to opportunity? Can you change this back to `using_account_history_mode_active_records`

2022-05-06 01:16 UTC, merged