[Release] Add History Mode Functionality to Salesforce Source Package
fivetran/dbt_salesforce_source pull request #40
Opened 2023-10-16 08:10 UTC by fivetran-avinash

## PR Overview
**This PR will address the following Issue/Feature:** This is updaets to include Salesforce History Mode in the existing Salesforce packages. 

**This PR will result in the following new package version:** 0.8.0

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt compile
- [x] dbt run –full-refresh
- [x] dbt run
- [x] dbt test
- [x] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked and tagged  (no existing issue, should i create one?)
- [x] You are assigned to the corresponding issue and this PR
- [] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [x] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [x] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [x] You have provided details below around the validation steps performed to gain confidence in these changes.

1) Run models as if no changes applied to ensure config works
2) Change configuration to run history models
3) Run specific history models
4) Apply passthrough columns
5) Apply filters to make sure date filter function on temp models work

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [x] indexed within dbt_project.yml
    - [x] indexed within integration_tests/dbt_project.yml
- [x] CHANGELOG has individual entries for each respective change in this PR
    
- [x] README updates have been applied (if applicable)
    
- [NA] DECISIONLOG updates have been updated (if applicable)
- [x] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [x] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
🍾

2023-10-16 21:00 UTC, fivetran-avinash commented on .buildkite/scripts/run_models.sh
> +dbt run --vars '{salesforce__account_history_enabled: true, salesforce__contact_history_enabled: true, salesforce__event_history_enabled: true, salesforce__lead_history_enabled: true, salesforce__opp
@fivetran-joemarkiewicz might not be necessary if we end up not using these variables.

2023-10-16 21:04 UTC, fivetran-avinash commented on integration_tests/seeds/sf_product_2_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,last_referenced_date,is_active,description,last_modified_date,record_type_id,product_code,_fivetran_synced,last_viewed_date,is_deleted,last_modified_by_
@fivetran-joemarkiewicz I did leave some custom fields in here for passthrough column testing, happy to consolidate if it's too many.

2023-10-16 21:04 UTC, fivetran-avinash commented on integration_tests/seeds/sf_opportunity_line_item_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,product_2_id,quantity,total_price,description,discount,last_modified_date,list_price,product_code,unit_price,_fivetran_synced,is_deleted,opportunity_id,
@fivetran-joemarkiewicz Also left some passthrough columns here as well.

2023-10-17 22:06 UTC, fivetran-joemarkiewicz commented
@fivetran-avinash please see PR #41 for my initial review of this update.

2023-10-25 14:02 UTC, fivetran-avinash commented
@fivetran-joemarkiewicz  New PR updates applied, in correspondence with @fivetran-joemarkiewicz 's [PR notes here](https://github.com/fivetran/dbt_salesforce_source/pull/41). Will respond in that PR with those particular updates.

2023-10-26 19:20 UTC, fivetran-joemarkiewicz requested changes
@fivetran-avinash thanks so much for working through these updates! I have a few comments mainly around documentation and removing the history model references for the tables we are no longer bringing through. Let me know once these are updated!

> Also am having some issues making the lineage line up (currently salesforce seeds are pointing toward salesforce history models. I'm wondering if I need to change my model configs).

I am not sure what you mean by this? Your setup looks good on my end and the generated docs didn't look off to me.

2023-10-26 19:20 UTC, fivetran-joemarkiewicz commented on README.md
> +Some of the end models in this package are materialized incrementally. We have chosen `insert_overwrite` as the default strategy for **BigQuery** and **Databricks** databases, as it is only available
```suggestion
The history models in this package are materialized incrementally. We have chosen `insert_overwrite` as the default strategy for **BigQuery** and **Databricks** databases, as it is only available for these dbt adapters. For **Snowflake**, **Redshift**, and **Postgres** databases, we have chosen `delete+insert` as the default strategy.
```

2023-10-26 19:20 UTC, fivetran-joemarkiewicz commented on README.md
> +## Optional: Utilizing Salesforce History Mode records
This is important enough to be it's own step. I would number it and then adjust the downstream numbers to account for the new section.

```suggestion
## (Optional) Step 4: Utilizing Salesforce History Mode records
```

2023-10-26 19:20 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- We have added history mode models in the [`models/history`](https://github.com/fivetran/dbt_salesforce_source/tree/main/models/history) folder [to support Fivetran's history mode feature](https://f
I think we should call out here that these are disabled by default.

2023-10-26 19:20 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- These models are disabled by default due to their size, so you will need to set the below variable configurations for each of the individual models you want to utilize in your `dbt_project.yml`.
We should call this out earlier in the section so customers are aware.

2023-10-26 19:20 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +## 🚨 Breaking Changes 🚨:
The salesforce history mode updates are not necessarily the breaking changes. These won't break for anyone who upgrades. Instead we should highlight them as feature updates. 

The breaking changes should only be those that existing customers need to be aware of that will break their transformations when upgrading.

2023-10-26 22:13 UTC, fivetran-avinash commented on README.md
> +See the below section for further configurations if you are leveraging Salesforce History Mode.
Removed.

2023-10-26 22:14 UTC, fivetran-avinash commented on README.md
> +We are aware that bringing in additional fields will be very process-heavy, so we do emphasize caution in making changes to your history mode connector. It would be best to batch as many field change
Moved.

2023-10-26 22:15 UTC, fivetran-avinash commented on README.md
> +      alias: "user_role_history_field_x"
Removed!

2023-10-26 22:16 UTC, fivetran-avinash commented on README.md
> +      alias: "lead_history_field_x"
I think they can all be removed since we are no longer utilizing passthrough columns on any of these history models?

2023-10-26 22:17 UTC, fivetran-avinash commented on dbt_project.yml
> +    lead_history: "{{ source('salesforce_history', 'lead') }}"
Gone!

2023-10-26 22:18 UTC, fivetran-avinash commented on dbt_project.yml
> +    user_role_history: "{{ source('salesforce_history', 'user_role') }}"
Out.

2023-10-26 22:19 UTC, fivetran-avinash commented on integration_tests/dbt_project.yml
> +    salesforce_user_role_history_identifier: "sf_user_role_history_data"
Removing

2023-10-26 22:20 UTC, fivetran-avinash commented on integration_tests/seeds/sf_event_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,id,_fivetran_synced,account_id,activity_date,activity_date_time,created_by_id,created_date,description,end_date_time,event_subtype,group_event_type,invi
deleted

2023-10-26 22:20 UTC, fivetran-avinash commented on integration_tests/seeds/sf_opportunity_line_item_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,product_2_id,quantity,total_price,description,discount,last_modified_date,list_price,product_code,unit_price,_fivetran_synced,is_deleted,opportunity_id,
deleted

2023-10-26 22:21 UTC, fivetran-avinash commented on integration_tests/seeds/sf_order_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,id,_fivetran_synced,account_id,activated_by_id,activated_date,billing_city,billing_country,billing_country_code,billing_geocode_accuracy,billing_latitud
deleted

2023-10-26 22:22 UTC, fivetran-avinash commented on integration_tests/seeds/sf_product_2_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,last_referenced_date,is_active,description,last_modified_date,record_type_id,product_code,_fivetran_synced,last_viewed_date,is_deleted,last_modified_by_
off it goes

2023-10-26 22:22 UTC, fivetran-avinash commented on integration_tests/seeds/sf_task_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,who_id,call_disposition,owner_id,subject,description,last_modified_date,what_count,_fivetran_synced,call_object,is_deleted,last_modified_by_id,system_mo
adios

2023-10-26 22:23 UTC, fivetran-avinash commented on integration_tests/seeds/sf_user_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,_fivetran_deleted,_fivetran_synced,account_id,alias,city,company_name,contact_id,country,department,email,first_name,id,individual_id,is_active,last_log
Wiped

2023-10-26 22:26 UTC, fivetran-avinash commented on integration_tests/seeds/sf_user_role_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,_fivetran_deleted,_fivetran_synced,developer_name,forecast_user_id,id,name,opportunity_access_for_account_owner,parent_role_id,rollup_description
Cleaned up!

2023-10-26 22:33 UTC, fivetran-avinash commented on integration_tests/seeds/sf_lead_history_data.csv
> +_fivetran_active,_fivetran_start,_fivetran_end,country,email_bounced_reason,email_bounced_date,owner_id,lead_source,converted_date,last_modified_date,master_record_id,last_modified_by_id,geocode_accu
Off it goes!

2023-10-26 22:39 UTC, fivetran-avinash commented on integration_tests/dbt_project.yml
> +    sf_event_history_data:
Off they go!

2023-10-26 22:40 UTC, fivetran-avinash commented on README.md
> +Some of the end models in this package are materialized incrementally. We have chosen `insert_overwrite` as the default strategy for **BigQuery** and **Databricks** databases, as it is only available
Updated!

2023-10-26 22:47 UTC, fivetran-avinash commented on CHANGELOG.md
> +- We have added history mode models in the [`models/history`](https://github.com/fivetran/dbt_salesforce_source/tree/main/models/history) folder [to support Fivetran's history mode feature](https://f
Moved the enable model variable section up.

2023-10-26 22:47 UTC, fivetran-avinash commented on CHANGELOG.md
> +- These models are disabled by default due to their size, so you will need to set the below variable configurations for each of the individual models you want to utilize in your `dbt_project.yml`.
Done!

2023-10-26 22:50 UTC, fivetran-avinash commented on CHANGELOG.md
> +## 🚨 Breaking Changes 🚨:
Updated!

2023-10-26 22:51 UTC, fivetran-avinash commented on README.md
> +## Optional: Utilizing Salesforce History Mode records
Steps updated!

2023-10-26 22:59 UTC, fivetran-avinash commented on CHANGELOG.md
> +- We have removed all `tmp` models and will use the `fivetran_utils.fill_staging_column` macro to compare directly to our source models in your schemas.
Updated!

2023-10-27 00:32 UTC, fivetran-avinash commented
@fivetran-joemarkiewicz New changes addressed! Ignore the generated docs issue, regeneration fixed it all.

2023-10-30 03:35 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-avinash thanks so much for working so hard through these updates! I had some very minor final comments to be addressed in this PR, but I felt they were pretty small and made more sense for me to fold them in via PR #43. Let me know if you have any questions around my final adjustments in the PR. If you have no comments feel free to merge it into your PR for ease.

Feel free to merge my PR into yours and regen docs. Once the PR is merged into yours, docs are regenerated, and buildkite is passing. This will be good to go!!

2023-10-31 16:02 UTC, merged