Bug/renamed columns option3
fivetran/dbt_salesforce_source pull request #48
Opened 2024-07-03 19:25 UTC by fivetran-catfritz

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
    
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-07-05 21:23 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz great work on this PR and very creative problem solving at work here! I have a few comments, suggestions, and questions in the review. Let me know if you would like to sync on any of my comments. Thanks!

2024-07-05 21:23 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +
Also be sure to include an under the hood reference to the validations you created.

2024-07-05 21:23 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account.sql
> +),
These are both just pulling from the latest results being materialized. In this case it would be dev.

This would need to change to be the following in order for it to properly compare dev vs prod.
```suggestion
with prod as (
    select *
    from {{ target.schema }}_salesforce_source_prod.stg_salesforce__account
),

dev as (
    select *
    from {{ target.schema }}_salesforce_source_dev.stg_salesforce__account
),
```

2024-07-05 21:23 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account.sql
> +),
However, when I make this change locally I see quite a large failure in this test 🤔. Do you see the same failure after making this change?

2024-07-05 21:23 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account.sql
> +),
I imagine this same comment persists for all the other validations

2024-07-08 15:18 UTC, fivetran-catfritz commented on integration_tests/tests/consistency/consistency_account.sql
> +),
🤦‍♀️ I'll update them all! Thanks, @fivetran-joemarkiewicz As for failures, it makes sense since it would only work on data from the old connector since it's expected that the coalesce changes would bring in the renamed values instead of nulls on data from a new connector. 

I had considered how to make a better test and originally made tests that query the information schema to confirm the column lists and datatypes for each table from dev and prod were the same. I scrapped that since I would have to write it for only bigquery, but I am thinking maybe that is a better solution. Any other ideas?

2024-07-08 16:30 UTC, fivetran-catfritz commented on macros/coalesce_rename.sql
> +    alias=column_dict[column_key]["alias"] | default(original_column_name),
Yes, exactly!

2024-07-08 17:26 UTC, fivetran-catfritz commented on integration_tests/tests/consistency/consistency_account.sql
> +),
From our discussion at standup, I will write the test to query the information schema!

2024-07-08 22:09 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz thank you for the review comments! I have made the changes, so it's ready for re-review.

2024-07-09 15:29 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz This is looking great! I tested on Snowflake (to ensure the camelcase wouldn't be an issue) and BigQuery and did not see any issues! This is nearly there for approval. I have one small request to revert the spark_utils change and also a more open ended question based on a comment you called out in your validation. We can sync on that after standup if you would like as it is a bit larger spanning question.

2024-07-09 15:29 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_all_tables_and_columns.sql
> +        while the dev is casted as dbt.type_numeric() and produces a value of "numeric" */
Isn't this technically a breaking change 👀. If the expected datatypes are changes between dev and prod, even if it is as small as float to numeric that could have downstream impacts. 

I see the below failures when I remove the case when statement.
![image](https://github.com/fivetran/dbt_salesforce_source/assets/74217849/e1c96ea5-539e-4b2d-a381-1ffa055d61f7)

Especially for fields like `*_revenue` I would want to be careful not to cause any unforeseen issues in a patch release if we are adjusting the datatype from float64 to numeric.

2024-07-09 16:01 UTC, fivetran-catfritz commented on packages.yml
> -  version: [">=0.3.0", "<0.4.0"]
My packages got messed up when I ran the consistency test script in the wrong folder. I'll put it back.

2024-07-09 16:10 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_all_tables_and_columns.sql
> +        while the dev is casted as dbt.type_numeric() and produces a value of "numeric" */
Based on our conversation in person, we will make this a breaking change and also cut a corresponding breaking change in the transform. Don't forget to make a callout as to why this is breaking in the CHANGELOG.

2024-07-10 01:12 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz I have updated this to a breaking change, and is ready for your review!

2024-07-10 01:12 UTC, fivetran-catfritz commented on integration_tests/tests/consistency/consistency_all_tables_and_columns.sql
> +        while the dev is casted as dbt.type_numeric() and produces a value of "numeric" */
Version now breaking!

2024-07-12 15:58 UTC, fivetran-joemarkiewicz reviewed
@fivetran-catfritz this is looking great, just one small comment and then I have some questions in the transform before approving.

2024-07-12 15:58 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_all_tables_and_columns.sql
> +            end as data_type
Now that we are making this a breaking change, would it make more sense to remove this case when statement? We know it will fail for this release (why it is breaking now), but it should not need this case statement for future updates and could risk us not catching datatype mismatches.

2024-07-12 21:48 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz Thanks for the review! I have updated the test.

2024-07-12 22:03 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-07-13 02:32 UTC, fivetran-avinash approved these changes
@fivetran-catfritz Amazing PR. Not a flaw I could see. LGTM!

2024-07-15 14:38 UTC, merged